### ISSUE TITLE
MultiZarrToZarr  got an unexpected keyword argument 'xarray_open_kwargs'

### ISSUE THREAD

**Issue by aladinor** [lsterzinger/fsspec-reference-maker-tutorial#4]
Hi all, 

I trying to run this example and I am having some issues with the **One JSON, multiple data files** section. Seems like the `MultiZarrToZarr` method is not receiving kwargs anymore. I am not sure if I am using kerchuncher wrong version or something similar (I used the environment.yml file to create the conda environment).  How do you think I can handle it? 

https://github.com/aladinor/notebooks/blob/origin/master/GOES_16_FSSPEC.ipynb 

Let me know your thoughts. 

Cheers, 

Alfonso.

**Comment by lsterzinger** [comment]
Hi @aladinor,

I'm guessing you're running the latest Kerchunk (0.0.6 currently). You can check by printing `kerchunk.__version__`.  In short, the `MultiZarrToZarr` class changed between 0.0.5 and 0.0.6. The correct way to format that block of code should now be:
```python
mzz = MultiZarrToZarr(
    json_list,
    remote_protocol="s3",
    remote_options={'anon':True},
    concat_dims = 't'
)
```

The documentation for the new `MultiZarrToZarr` can be found here https://fsspec.github.io/kerchunk/reference.html#kerchunk.combine.MultiZarrToZarr

**Comment by aladinor** [comment]
Hi @lsterzinger, 

You are right. I think I installed a new version of kerchunk. However, after playing around I figured out just to pass the `conca_dims` parameter and it worked. 

Thanks so much for your time and help!
